---					

- name: configure spines          
  hosts: spines				
  connection: network_cli			
  gather_facts: no				
  become: yes				
  become_method: enable			
  vars:					
    ansible_network_os: onyx			
  roles:					
     - spines				          				          

- name: configure leafs		          
  hosts: leafs				
  connection: network_cli			
  gather_facts: no				
  become: yes				
  become_method: enable			
  vars:					
    ansible_network_os: onyx			
  roles:					
     - leafs				          
